### ISSUE TITLE
Do we have to add External SVG Sprite dependency?

### ISSUE THREAD

**Issue by jarodtaylor** [stldo/gatsby-plugin-svg-sprites#4]
I'm not sure if your README is missing a step, but your current README doesn't work. I don't get any errors, but the SVG sprite is still not injected into the DOM. Am I missing something?

**Comment by stldo** [comment]
Hi! It's working fine here. Could you please share the SVG file you're trying to import?

**Comment by jarodtaylor** [comment]
I have multiple SVG in a folder. I import them and I see the props (url, viewBox, etc) but they don't work because the Sprite itself is not ever injected into the DOM (like most svg sprite solutions).

**Comment by jarodtaylor** [comment]
Ah, never mind. I messed up the syntax. It's working. Thanks!
